apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: addsvc
  name: addsvc
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: addsvc
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service": "addsvc"
        "consul.hashicorp.com/connect-service-port": "8021"
        "consul.hashicorp.com/connect-service-protocol": "grpc"
    spec:
      containers:
        - env:
            - name: QS_ADDSVC_GRPC_PORT
              value: "8021"
            - name: QS_ADDSVC_HTTP_PORT
              value: "8020"
            - name: QS_ADDSVC_LOG_LEVEL
              value: info
            - name: QS_ZIPKIN_V2_URL
              value: http://zipkin:9411/api/v2/spans
          image: cage1016/gokitconsulk8s-addsvc:latest
          name: gokitconsulk8s-addsvc
          resources: {}
      restartPolicy: Always
status: {}
