apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: foosvc
  name: foosvc
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: foosvc
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service": "foosvc"
        "consul.hashicorp.com/connect-service-port": "7021"
        "consul.hashicorp.com/connect-service-protocol": "grpc"
        "consul.hashicorp.com/connect-service-upstreams": "addsvc:8021"
    spec:
      containers:
        - env:
            - name: QS_ADDSVC_LOG_LEVEL
              value: info
            - name: QS_ADDSVC_URL
              value: "localhost:8021"
            - name: QS_FOOSVC_GRPC_PORT
              value: "7021"
            - name: QS_FOOSVC_HTTP_PORT
              value: "7020"
            - name: QS_ZIPKIN_V2_URL
              value: http://zipkin:9411/api/v2/spans
          image: cage1016/gokitconsulk8s-foosvc
          name: gokitconsulk8s-foosvc
          resources: {}
      restartPolicy: Always
status: {}
