---
apiVersion: v1
kind: Service
metadata:
  name: ingress-http
spec:
  type: LoadBalancer
  selector:
    app: ingress-http
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-http-configmap
data:
  zipkin: |
    {
      "service_name": "nginx",
      "collector_host": "zipkin",
      "collector_port": 9411
    }

  config: |
    load_module modules/ngx_http_opentracing_module.so;

    events {
      worker_connections  1024;
    }
    http {
      opentracing_load_tracer /usr/local/lib/libzipkin_opentracing_plugin.so /etc/nginx/zipkin.json;
      opentracing on;

      upstream website {
        keepalive 100;
        server localhost:8080;
      }
      upstream router {
        keepalive 100;
        server localhost:8000;
      }
      server {
        location / {
          proxy_http_version 1.1;
          proxy_pass http://website;
          proxy_set_header Host $host;

          opentracing_propagate_context;
        }

        location ~ ^/api(/.*)?$ {
          proxy_http_version 1.1;
          proxy_pass http://router$1$is_args$args;
          proxy_pass_request_headers on;

          opentracing_propagate_context;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingress-http
  labels:
    app: ingress-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-http
  template:
    metadata:
      name: ingress-http
      labels:
        app: ingress-http
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service": "nginx-http"
        "consul.hashicorp.com/connect-service-upstreams": "website:8080,router-http:8000"
    spec:
      volumes:
        - name: config
          configMap:
            name: ingress-http-configmap
      initContainers:
        - name: init-opentracing
          image: cirrusci/wget
          command: ['sh', '-c', 'wget -O - https://github.com/rnburn/zipkin-cpp-opentracing/releases/download/v0.5.2/linux-amd64-libzipkin_opentracing_plugin.so.gz | gunzip -c > /usr/local/lib/libzipkin_opentracing_plugin.so']
      containers:
        - name: ingress-http
          image: opentracing/nginx-opentracing
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: config
            - name: config
              mountPath: /etc/nginx/zipkin.json
              subPath: zipkin