apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: gokitconsulk8s-router
  name: gokitconsulk8s-router
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: gokitconsulk8s-router
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: gokitconsulk8s-router
        app: gokitconsulk8s-router
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service": "router"
        "consul.hashicorp.com/connect-service-upstreams": "addsvc:8021,foosvc:7021"
        "consul.hashicorp.com/connect-service-port": "8000"
    spec:
      containers:
        - env:
            - name: QS_ROUTER_LOG_LEVEL
              value: info
            - name: QS_ADDSVC_URL
              value: localhost:8021
            - name: QS_FOOSVC_URL
              value: localhost:7021
            - name: QS_ROUTER_GRPC_PORT
              value: "8001"
            - name: QS_ROUTER_HTTP_PORT
              value: "8000"
            - name: QS_ZIPKIN_V2_URL
              value: http://zipkin:9411/api/v2/spans
          image: cage1016/gokitconsulk8s-router
          name: gokitconsulk8s-router
          resources: {}
      restartPolicy: Always
status: {}
